# Generated by Django 5.2.3 on 2025-07-26 13:38

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.UUIDField(default=uuid.UUID('617008cc-74fb-4294-94dd-4456016ce1be'), primary_key=True, serialize=False, unique=True)),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('updated_time', models.DateTimeField(auto_now=True)),
                ('material_name', models.CharField(max_length=150, unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.UUIDField(default=uuid.UUID('617008cc-74fb-4294-94dd-4456016ce1be'), primary_key=True, serialize=False, unique=True)),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('updated_time', models.DateTimeField(auto_now=True)),
                ('product_name', models.CharField(max_length=150, unique=True)),
                ('product_code', models.CharField(max_length=150, unique=True)),
            ],
            options={
                'verbose_name': 'product',
                'verbose_name_plural': 'products',
                'db_table': 'products',
            },
        ),
        migrations.CreateModel(
            name='ProductMaterial',
            fields=[
                ('id', models.UUIDField(default=uuid.UUID('617008cc-74fb-4294-94dd-4456016ce1be'), primary_key=True, serialize=False, unique=True)),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('updated_time', models.DateTimeField(auto_now=True)),
                ('quantity', models.IntegerField(validators=[django.core.validators.MinValueValidator(limit_value=1, message='Quantity must be greater than 0')])),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_materials', to='main.material')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_materials', to='main.product')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='WareHouse',
            fields=[
                ('id', models.UUIDField(default=uuid.UUID('617008cc-74fb-4294-94dd-4456016ce1be'), primary_key=True, serialize=False, unique=True)),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('updated_time', models.DateTimeField(auto_now=True)),
                ('remainder', models.IntegerField(validators=[django.core.validators.MinValueValidator(limit_value=0, message='Quantity must be greater than 0')])),
                ('price', models.IntegerField(validators=[django.core.validators.MinValueValidator(limit_value=1, message='Quantity must be greater than 0')])),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ware_houses', to='main.product')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
