# Generated by Django 5.2.3 on 2025-07-26 16:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_material_id_alter_product_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productmaterial',
            name='quantity',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(limit_value=1, message='Quantity must be greater than 1')]),
        ),
        migrations.AlterField(
            model_name='warehouse',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
