# Generated by Django 5.2.3 on 2025-07-26 16:06

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_productmaterial_quantity_alter_warehouse_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='warehouse',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True),
        ),
    ]
