# Generated by Django 5.2.3 on 2025-07-27 06:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_product_product_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productmaterial',
            name='quantity',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(limit_value=1, message='Quantity must be greater than 1')]),
        ),
    ]
