# Generated by Django 5.2.3 on 2025-07-31 12:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alter_productmaterial_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_code',
            field=models.CharField(blank=True, editable=False, max_length=6, unique=True),
        ),
        migrations.AlterField(
            model_name='productmaterial',
            name='quantity',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(limit_value=0, message='Quantity must be greater than 1')]),
        ),
    ]
