# Generated by Django 5.2.3 on 2025-07-31 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_alter_product_product_code'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='productmaterial',
            constraint=models.UniqueConstraint(fields=('product', 'material'), name='ProductMaterial'),
        ),
    ]
